### PR TITLE
upgrade datafusion & arrow

### PR DESCRIPTION
**Pull request by xhwhis**
upgrade datafusion to 42 and arrow to 53.
the `.taplo.toml` file is copied from `dadafusion`.
BTW, I think we don't need `datafusion` and `arrow` dependencies, just need subcrates like `dadafusion-expr` and `arrow-array`. If you agree, I would do this.

### CODE REVIEW

**Review by hozan23 — APPROVED** [review]
Thanks @xhwhis.

**Comment by xhwhis** [comment]
> @xhwhis确实，这将有助于减少依赖项数量并减少编译时间。您可以继续这样做。

@hozan23 done

**Comment by hozan23** [comment]
Hey @xhwhis  

I am sorry but I believe this is not the ideal way to manage dependencies in rust. I thought you intended to use Cargo `features` to minimize the dependencies. Your current approach, where you're importing the subcrates, won't make a difference since you're also importing the main crate, `datafusion`, It will also make it much harder to manage dependencies. It's best to reduce dependencies using Cargo `features` for the main crate. You can find the available `features` for `datafusion` [here](https://github.com/apache/datafusion/tree/main?tab=readme-ov-file#crate-features), which allows you to include only the necessary `features` (crates) for each crate in our repository.

**Comment by xhwhis** [comment]
merge PR #59, close it.

**Pull request closed without merging**
