### PR TITLE
feat: federate expression subqueries

### LINKED ISSUE #31: Support table scans in expressions (subquery)
We're currently not walking expressions in the `FederationAnalyzerRule`. This means any table scans in expressions are not handled correctly. For example, this means subqueries in a projection or filter are not handled. A first implementation could find table scans in the expressions and incorporate them into `optimize_recursively`.

### PR DESCRIPTION
**Pull request by sardination**
Closes #31

Recursively optimize subqueries in expressions as well.

### CODE REVIEW

**Comment by backkem** [comment]
Hi @sardination, thank you for having a loot at this.

`optimize_recursively` recursively walks over the plan and tries to find the largest possible sub-plans that can be federated by one remote. The PR as it stands now, adds the subqueries to the recursion but, as your TODO comment mentions, it doesn't incorporate it in the logic to determine the largest possible sub-plans yet.

To make this work, I was thinking in the direction of building a custom stack to hold the inputs at a specific plan depth, similar to [ExprIdentifierVisitor](https://github.com/apache/datafusion/blob/5d3bbaa3233523819d823e69139cd522db715cae/datafusion/optimizer/src/common_subexpr_eliminate.rs#L612). That way the entire function can be re-written as a `TreeNodeVisitor` (which exists for expressions while the `.inputs()` method doesn't). I need to find more time to complete this though.

**Comment by backkem** [comment]
I noticed the `ScalarSubquery`s aren't supported by the physical planner. They are replaced in the `scalar_subquery_to_join` optimiser. I guess this means we need to re-write the analyzer to an optimizer and schedule it after the `scalar_subquery_to_join` one.

**Comment by backkem** [comment]
Continued in #37.

**Comment by philippemnoel** [comment]
Thank you for picking this up @backkem!

**Pull request closed without merging**
